release/6.0: Unify docs build into a single build, support proper multiversion links (#93)
* Add prerequisite for Git LFS to develop OSMO (#64)

* Remove trigger response (#65)

* Fix readme docs link (#68)

* Enforce PR description in CI (#69)

* Enforce PR description in CI

* Add pull_request edit event

* Move to its own file so checks don't run for every edit

* formatting

* add reopened event

* Ethany/isaac lab examples (#66)

* Update Isaac Sim Workflow

* Add Isaac Lab Multi GPU/Node Samples

* #71 - Add a root documentation page (#72)

* #71 - Add a root documentation page

* simplify subdir overrides

* fix font

* restore fallback fonts

* fix deployment options card height

* reorganize user guide landing

* Make the SVG on the docs root page smaller (#74)

* Adds multiversion support for docs (#40)

* Use sphinx-multiversion so multiple versions of the docs are built

---------

Co-authored-by: Fernando Luo <fernandol@nvidia.com>

* docs: fix doc links after multiversion support (#76)

* #78 - docs: temp fix for multiversion links (#80)

* docs: fix broken user_guide multiversion links

* Revert img src change

Co-authored-by: RyaliNvidia <ryali@nvidia.com>

---------

Co-authored-by: RyaliNvidia <ryali@nvidia.com>

* quick-start: make apk fail fast (#84)

apk add may fail due to things like transient upstream unavailability.
Prior to this change we would get stuck in an infinite loop of trying
to invoke curl. This change makes the simplest change to make it fail
and let K8s handle restarting the init container.

* Make docs root page use a grid (#85)

* Make docs root page use a grid

* remove main branch specifier

* Remove unused file from root docs glob (#87)

* Add ci-docs step to run bazel tests on docs/ changes (#88)

* Add ci-docs step to run bazel tests on docs/ changes

* only run build - not test

* Resolve broken/redirect links in readme and documentation (#89)

* #82 - Add link checking to documentation (#83)

* Add link checking to documentation

* Verified check

* Fix artifacts upload

* Resolve issue

* update workflows logic

* docs: unify sphinx build, fix multiversion links

* Unify Sphinx build to build as one project instead
  of separate User Guide and Deployment Guide builds
* Change hard-coded URLs to use Sphinx roles so
  the correct multiversion link can be interpolated
  at build time

The goal of this change is to make the links in our docs
version-aware after moving to multiversion docs in
https://github.com/NVIDIA/OSMO/pull/40. Normally the
way to do this is to reference roles like `:doc:` and
`:ref:` instead of hard-coding URLs, but since we have
cross-guide links we also have to unify the Sphinx build
to make the builds aware of roles across all our docs.

* fix hard-coded links

* prepend main to some other hard-coded links

* fix missing sidebar

* cleanup multibuild state

* fix sidebar toc by overriding nvidia-sphinx-theme

* only linkcheck root now

* add note in sidebar-nav-bs

* restore custom index css to remove sidebar

* fix broken images

* fix multiversion build

* add copyright

* move usages from doc to ref

---------

Co-authored-by: Ethan Look-Potts <elookpotts@nvidia.com>
Co-authored-by: Fernando L <fernandol@nvidia.com>
Co-authored-by: RyaliNvidia <ryali@nvidia.com>
Co-authored-by: ethany-nv <ethany@nvidia.com>

diff --git a/deployments/charts/quick-start/values.yaml b/deployments/charts/quick-start/values.yaml
--- a/deployments/charts/quick-start/values.yaml
+++ b/deployments/charts/quick-start/values.yaml
@@ -743,6 +743,9 @@ backend-operator:
         - sh
         - -c
         - |
+          # Mostly used to fail fast if there is a transient issue with apk add.
+          # For simplicity let K8s restart and retry the container.
+          set -e
           apk add --no-cache curl jq
           echo "Waiting for backend-operator-token to be created..."
           until curl -s http://quick-start.osmo/api/auth/access_token/service | jq -e '.[] | select(.token_name == "backend-operator-token")' >/dev/null 2>&1; do
@@ -791,6 +794,9 @@ backend-operator:
         - sh
         - -c
         - |
+          # Mostly used to fail fast if there is a transient issue with apk add.
+          # For simplicity let K8s restart and retry the container.
+          set -e
           apk add --no-cache curl jq
           echo "Waiting for backend-operator-token to be created..."
           until curl -s http://quick-start.osmo/api/auth/access_token/service | jq -e '.[] | select(.token_name == "backend-operator-token")' >/dev/null 2>&1; do
